### ISSUE TITLE
Hi there, love your work!

### ISSUE THREAD

**Issue by tanchongmin** [AIRI-Institute/AriGraph#1]
I have read your paper on AriGraph and love what you all are doing to adaptively learn from the environment.

I am creating an LLM-based Agentic Framework as well, TaskGen (https://github.com/simbianai/taskgen), and I believe there are synergistic ways we can incorporate features of the KG generation and conditioning into a learning system as well in there.

Would you all be open for a chat? Would love to talk more about such an adaptable learning system. 

Kindly let me know how to contact you all :)

Here is my contact:
https://www.linkedin.com/in/john-chong-min-tan-94652288/

**Comment by PetrAnokhin** [comment]
Greetings, John!

Apologies for the delayed response.

We're thrilled to hear that you enjoyed our paper! Actually, I checked out your videos on LLMs and knowledge graphs while we were developing our project. It was very helpfull and informative. Thank you for putting out such valuable content for the ML community!

We're definitely up for a chat! We'll take a closer look at TaskGen and reach out to you on LinkedIn.

Here is my contacts: 
https://www.linkedin.com/in/petr-anokhin-2b295a318/
petranokhin@gmail.com
